var namespace_greet_1_1_data_structure_v3_1_1_exceptions =
[
    [ "CarbonRatioNANException", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_carbon_ratio_n_a_n_exception.html", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_carbon_ratio_n_a_n_exception" ],
    [ "DensityValueNANException", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_density_value_n_a_n_exception.html", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_density_value_n_a_n_exception" ],
    [ "FormulaResultNANException", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_formula_result_n_a_n_exception.html", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_formula_result_n_a_n_exception" ],
    [ "HeatingValueNANException", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_heating_value_n_a_n_exception.html", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_heating_value_n_a_n_exception" ],
    [ "InconsistantUnitsException", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_inconsistant_units_exception.html", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_inconsistant_units_exception" ],
    [ "InputAmountException", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_input_amount_exception.html", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_input_amount_exception" ],
    [ "InvalidParameterReferenceException", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_invalid_parameter_reference_exception.html", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_invalid_parameter_reference_exception" ],
    [ "MarketValueNANException", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_market_value_n_a_n_exception.html", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_market_value_n_a_n_exception" ],
    [ "SulfurRatioNANException", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_sulfur_ratio_n_a_n_exception.html", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_sulfur_ratio_n_a_n_exception" ],
    [ "UnitConversionException", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_unit_conversion_exception.html", "class_greet_1_1_data_structure_v3_1_1_exceptions_1_1_unit_conversion_exception" ]
];